# **Data Analysis**
***

## Container Application




::: {.panel-tabset}

### Docker Desktop

Ask learners to try to run the analysis, editing the run all script to include the summary stat we've discussed

### Docker through a CLI

Ask learners to try to run the analysis, editing the run all script to include the summary stat we've discussed

:::

:::{.think_question}
::::{.think_question_header}
Question opportunity
::::
::::{.inner_block}
Pose a question about the data analysis.
<details><summary>Answer</summary>
You can use a collapsible details section to provide an answer
</details>
::::
:::

::: {.column-margin}
We might use a column margin note to add an equation or some other annotation for learners or educators.
:::

In this section we can discuss that someone else (maybe the person validating the work for resubmission) can use the container to run the analysis and get the exact same results and plot that you made because of the container. Specifically, what should you share with someone so they can rerun the analysis?

```{r, echo = FALSE}
ottrpal::include_slide("https://docs.google.com/presentation/d/1EFnuBBFlqjod7S1OlOoj_9-29nPO3ZhL6iJ-Pf8xzpg/edit?slide=id.g3f0102bcf57_7_5#slide=id.g3f0102bcf57_7_5")
```

```{.dockerfile filename="Dockerfile"}
{{< include resources/dockerfiles/activity/Dockerfile >}}
```

```{.bash filename="run_analysis.sh"}
{{< include resources/analysis_scripts/run_analysis.sh >}}
```

:::{.reproducibility_box}
::::{.reproducibility_box_header}
Reproducibility considerations
::::
::::{.inner_block}
Having a "run all" script that specifies what scripts were used and in what order for the analysis is a best practice for reproducibility [@Wilson_etal_2017].
::::
:::

## Container Infrastructure

::: {.panel-tabset}

### Docker Desktop

Sharing the container

### Docker through a CLI

Sharing the container

:::

We'll also discuss how to document where the scripts are, how to mount a volume (with analysis scripts) and point out that the validator can get the same results as the learner did by running the `run_analysis.sh` script.

Add a reproducibility box about pushing the new / adjusted scripts and plots as well as the documentation to the scaffold repo that they "used as a template/cloned" if they did the earlier extra reproducibility step.


***
