<!--
Describe any limitations that exist in this analysis whether it be due to the data itself, methods used, nature of the topic, etc.
You can list more than 2
See the following example from a previous case study: https://www.opencasestudies.org/ocs-bp-opioid-rural-urban/#Limitations
-->

# **Limitations**
***

There are some important considerations regarding this data analysis to keep in mind:

This case study specifically uses the technology Docker to build containers and run analyses within these isolated environments, on a local machine.

*Limitations regarding containerization and the scope of this case study:*

This case study does **not** describe how to

  * develop containers from the ground up
  * use containers within a workflow using tools like Nextflow or Workflow Description Language (WDL)
  * use containers to support a remote analysis (e.g., in the cloud)
  * use containers to deploy or support an application
  * use technologies other than Docker such as Apptainer or Singularity

Docker is a widely used tool for containerization. However, it is not the most appropriate tool for all use cases and within all contexts. For example, institutional High Performance Computing (HPC) often utilizes Apptainer due to its need of fewer user privileges (e.g., greater security). As a software tool, the long-term availability of Docker is not guaranteed. Containerization and the principles discussed within this case study will remain integral to reproducible research especially for dispersed teams. However, the specific technologies used to implement these principles may change over time and within different contexts.

*Limitations regarding the data analysis and using aggregated data:*

This case study focuses on practicing best practices in using containers to support reproducible and extensible scientific analyses. To support this goal, the example analysis is a straightforward visualization of narrow scope data. There could be additional context and characteristics (e.g., quality) about the data that are not considered or visualized within this analysis.

In addition, the harmonization of aggregated data requires careful consideration to ensure that data from multiple, different sources is both compatible and comparable [@Cheng_etal_2024]. Steps involved in data harmonization include mapping related variables across datasets, adjusting scales, units, or formats for proper comparison, and reducing bias due to differences in data collection. Harmonization is not performed within this case study. Typically, meta-analyses are synthesizing summarized information rather than aggregating the underlying, raw data [@Cheng_etal_2024]. If using this curated resource to aggregate the underlying data, carefully consider what data harmonization may be appropriate [@Nan_etal_2022].

***
