
## **Objectives Map**

::: {.callout-note collapse="true" title="Objectives Map: Where It Is Covered"}


| Learning Goal          | Applications / Practice                            | Location                |
| :----------------------------------- | :-------------------------------------------------------------|:-----------------------|
| Discuss ways in which containerization promotes reproducibility within collaborative scientific research. | Comprehend the benefits of containerization for collaborative scientific research. | [Introduction to Containers](https://www.opencasestudies.org/ocs-bio-containers/#introduction-to-containers) |
| Describe how containerization is one of several tools to increase the reproducibility of scientific research. | Understand that other options besides containerization can be used to promote reproducibility by reporting or sharing software versions.  | [Introduction to Containers](https://www.opencasestudies.org/ocs-bio-containers/#introduction-to-containers) |
| Employ multiple reproduicibility best practices together within the context of containerization. | Apply additional considerations or steps which can be taken to increase reproducibility including utilizing file organization, version control for files, DRY principles when writing code, a run all script to define an analysis, and pull requests for integrating analysis changes into a repository. | [Data Import](https://www.opencasestudies.org/ocs-bio-containers/#data-import-1), [Data Visualization](https://www.opencasestudies.org/ocs-bio-containers/#data-visualization-1), and [Data Analysis](https://www.opencasestudies.org/ocs-bio-containers/#data-analysis-1) |
| Evaluate what should or should not be included in a container. | Assess what is in a container and what shouldn't be in a container | [Introduction to Containers](https://www.opencasestudies.org/ocs-bio-containers/#introduction-to-containers) and [Data Exploration](https://www.opencasestudies.org/ocs-bio-containers/#data-exploration-1)|
| Identify contexts where containerization (potentially with Docker) is not appropriate or needed. | Recognize contexts where containerization isn't necessary or using Docker would not be appropriate | [Introduction to Containers](https://www.opencasestudies.org/ocs-bio-containers/#introduction-to-containers) |
| Practice the containerization process to reproduce, extend, and share a data analysis and its results. | Use a container to reproduce an analysis, extend an analysis, and then share. | [Data Import](https://www.opencasestudies.org/ocs-bio-containers/#data-import-1), [Data Wrangling](https://www.opencasestudies.org/ocs-bio-containers/#data-wrangling-1), [Data Visualization](https://www.opencasestudies.org/ocs-bio-containers/#data-visualization-1), and [Data Analysis](https://www.opencasestudies.org/ocs-bio-containers/#data-analysis-1) |
| Verify that results or outputs match expectations. | Use and look at print messages output from an analysis as well as files that are created. | [Data Import](https://www.opencasestudies.org/ocs-bio-containers/#data-import-1), [Data Wrangling](https://www.opencasestudies.org/ocs-bio-containers/#data-wrangling-1), and [Data Visualization](https://www.opencasestudies.org/ocs-bio-containers/#data-visualization-1) |
| Explain how statistical power is impacted by the number of samples in an analysis. | Learn about the connection between number of samples and statistical power. | [Context](https://www.opencasestudies.org/ocs-bio-containers/#context) |
| Recognize the need and considerations for data harmonization when utilizing multiple data sources. | Learn about considerations when using a curated data resource or data collection. | [Context](https://www.opencasestudies.org/ocs-bio-containers/#context) and [Ethical Considerations](https://www.opencasestudies.org/ocs-bio-containers/#ethical-considerations) |
| Describe how the number of observed metabolites is impacted by the number of samples in a dataset. | Describe the relationship or trend between variables that are visualized.  | [Data Visualization](https://www.opencasestudies.org/ocs-bio-containers/#data-visualization-1) |
| List the value and potential applications of data collections or curated data resources. | Learn about benefits of curated data resources or data collections. | [Context](https://www.opencasestudies.org/ocs-bio-containers/#context) |
| Explain the limitations and cautions associated with using a data collection or curated data resource for your own work. | Learn about considerations when using a curated data resource or data collection. | [Context](https://www.opencasestudies.org/ocs-bio-containers/#context) and [Ethical Considerations](https://www.opencasestudies.org/ocs-bio-containers/#ethical-considerations) |
| Relate the utility of pairing microbiome and metabolome data for biological research. | Learn about the connections between these two types of data. | [Context](https://www.opencasestudies.org/ocs-bio-containers/#context) |
| Build visualizations to communicate the relationship among variables in a table. | Produce a data visualization that displays the relationship between different variables. | [Data Visualization](https://www.opencasestudies.org/ocs-bio-containers/#data-visualization-1) |

:::

