# **Packages and Setup**
***

Before we get into fetching images, running containers, and running analyses, we want to describe the R packages that we'll use in this case study, or that are used within the analysis scripts for the project with Collab O. Rator.

Package    | Use
---------- |-------------
[here](https://cran.r-project.org/web/packages/here/refman/here.html){target="_blank"} | Constructs paths within project
[tabulapdf](https://cran.r-project.org/web/packages/tabulapdf/refman/tabulapdf.html){target="_blank"}      | Extract data from a PDF
[tidyverse](https://cran.r-project.org/web/packages/tidyverse/refman/tidyverse.html){target="_blank"} | Data wrangling
[ggplot2](https://cran.r-project.org/web/packages/ggplot2/refman/ggplot2.html){target="_blank"}      | Visualize data
[patchwork](https://cran.r-project.org/web/packages/patchwork/refman/patchwork.html){target="_blank"} | Combining multiple plots


The first time we use a function, we will use the `::` to indicate which package we are using. Unless we have overlapping function names, this is not necessary, but we will include it here to be informative about where the functions we will use come from.

::: {.emphasis_block}
`tabulapdf` is an example of a package that you may want to use a container for because of dependencies. `tabulapdf` requires Java which you may or may not have installed in your system. Though dependency needs can get much more complex.
:::

This case study is focusing on **how to work with containers while performing a data analysis** (the project from Collab O. Rator described earlier in the Motivation section). Therefore, every subsequent section will have two portions:

1. **Container Infrastructure Activities**: Exploring container specific concepts and performing containerization tasks to support the project.
2. **Container Application Activities**: Working with data with the container (whose infrastructure you've set up by doing the Container Infrastructure Activities).
    
::: {.panel-tabset}

## Data<br>Import

Portion of section           | Description of activity
-----------------------------| -----------------------
**Container Infrastructure** | "Importing" a **container image** from Docker Hub as well as retrieving analysis scripts from GitHub; then running the image while mounting the volume with the analysis scripts.
**Container Application**    | Using the running container (retrieved in the previous portion of Data Import) to "import" the **data** from the PDF version of Table 1 of the paper.

## Data<br>Exploration

Portion of section           | Description of activity
-----------------------------| -----------------------
**Container Infrastructure** | "Exploring" the **Dockerfile** of **the container image** retrieved from Docker Hub in the Data Import section.
**Container Application**    | "Exploring" the **raw data** which was retrieved from the PDF version of Table 1 of the paper in the Data Import section. We will discuss how containers can be a part of this.

## Data<br>Wrangling

Portion of section           | Description of activity
-----------------------------| -----------------------
**Container Infrastructure** | Using the running container, "wrangling" the **raw data** that was retrieved and explored in previous sections according to what was observed in the Data Exploration section.
**Container Application**    | Wrangling the **Dockerfile** for **the container image** to add a package that will help with the Data Visualization task.

## Data<br>Visualization

Portion of section           | Description of activity
-----------------------------| -----------------------
**Container Infrastructure** | Building the modified **Dockerfile** from the Data Wrangling section, **running the image** while **mounting the volume** with the analysis scripts. Additionally, learners will "visualize" this **containerization process** as a flowchart.
**Container Application**    | Using the running container (set up in the previous portion of Data Visualization) to "visualize" the **wrangled data** from the Data Wrangling section.

## Data<br>Analysis

Portion of section           | Description of activity
-----------------------------| -----------------------
**Container Infrastructure** | Using the running container, adjusting the "analysis" to include a summary statistic about the **wrangled data** and visualization as well as a script that runs the whole process so that the analysis can be more easily validated.
**Container Application**    | Sharing the **container**, adjusted "analysis", and appropriate documentation with collaborators.

:::

In all cases, code for the tasks within the **Container Application** portions will be provided for learners since the focus of this case study is **how to work with containers**, not how to code with R. 



