# **Continued Learning**

***

## Reinforcement Exercises

***

A good way to practice the skills from this case study is to practice the containerization process again.

We noted that in the combined scatter plot, text labels were both cutoff along axes edges and text labels were overlapping each other. The `ggrepel` package can be useful in fixing these problems.

* Add `ggrepel` to the Dockerfile.
* {{< glossary "Build" display = "build">}} the Dockerfile.
* Run the image, mounting the `ocs-bio-containers-scaffold-main` volume as you've done previously.
* Look at the `continued_learning_scripts/refinement/03_alt_visualization_ggrepel.R` script within the `ocs-bio-containers-scaffold-main` directory and try to understand what it's doing.
* Use the `continued_learning_scripts/refinement/03_alt_visualization_ggrepel.R` script to create a modified visualization to fix the overlapping and cutoff text labels.
* Be sure to clean up your container and image.


## Advancement Exercises

***

### Beginner

The table provides cohort descriptions about each dataset that are lost within the scatter plot. We can add some interactivity with `plotly` that will allow us to display info like the dataset description when we hover over the points. 

* Edit the Dockerfile to install the [`plotly`](https://github.com/plotly/plotly.R) and [`htmlwidgets`]( https://github.com/ramnathv/htmlwidgets) packages from GitHub. We recommend using either `Pak` or the `littler` `installGithub.R` helper script to install from GitHub).
* Build the Dockerfile.
* Run the image, mounting the `ocs-bio-containers-scaffold-main` volume as you've done previously.
* Look at the `continued_learning_scripts/beginner/03_alt_visualization_plotly.R` script within the `ocs-bio-containers-scaffold-main` directory and try to understand what it's doing. It may be helpful to ask AI to explain what various steps are doing.
* Use the `continued_learning_scripts/beginner/03_alt_visualization_plotly.R` script to create an interactive version of the scatter plots.
* Open the resulting `.html` file and inspect the output.
* Can you edit the `run_analysis.sh` script or create a new one to run the whole process including the creation of the interactive plot (`.html` file)?
* Be sure to clean up your container and image.

### Intermediate

Create a Dockerfile from scratch which could be used to perform a similar analysis with Python.

Packages that you should add to the Dockerfile include:

  * https://pypi.org/project/tabula-py/
  * pandas
  * matplotlib
  * https://github.com/ponnhide/patchworklib
  * https://github.com/Phlya/adjustText

Consult the [ITN's Reproducibility Capstone Project Course for additional guidance](https://hutchdatascience.org/reproducibility_capstone/building-a-docker-image.html#phase-2-dockerfile-development) on developing a Dockerfile from scratch.

Alternatively, you may be able to find an image on Docker Hub that would meet your needs.

After creating the Dockerfile, you may be interested in testing it out. Recreate the analysis done in R for this case study using Python. Can you successfully recreate the original outputs using the refactored code (e.g., robustness)?

:::{.ai_box}
::::{.ai_box_header}
AI use considerations
::::
::::{.inner_block}
<u>Context</u>
AI can be especially useful in refactoring code from one language to another. For each script, provide an AI chatbot with the goal of refactoring the code, which relevant Python packages will be available, the original R code, and what the goal of that code is.

<u>Suggested Prompt:</u>

```{ .default .code-overflow-wrap code-line-numbers="false" }
I would like to refactor this R script that [goal of the code], to create a python equivalent. I would like to use the following Python packages within the scripts [Python packages]. 
```


<u>Validation:</u>
Test the scripts that AI suggests within the container created from your new Dockerfile. Do you successfully create the outputs seen from the R analysis?

::::
:::


### Advanced

[Build a GitHub action](https://hutchdatascience.org/reproducibility_capstone/building-a-github-action.html) that uses the original container pulled from Docker Hub to run the `01_extract_data.R` script. Can you extend the GitHub action to perform the whole analysis with the second container ([available from Docker Hub here](https://hub.docker.com/r/bioocs/ocs-bio-containers-wrangling)? 

***
