---
title: "**Biomedical Open Case Studies: Using containers for collaborative, reproducible research**"
bibliography: resources/references.bib
include-sections:
  stat-los: true
  lo-map: true
  data-import: true
  data-exploration: true
  data-wrangling: true
  data-viz: true
  data-analysis: true
  main-q-table: true
---

<!--
  Update above to exclude optional or new sections by changing from true to false.
  Update the various qmd documents below with each component of a Bio-OCS case study.
  Besides filling in the title in the header of this document, no other changes should be necessary within this file.
  Use the `include-sections` within the header to toggle section inclusion/exclusion as needed.
  For documentation on quarto syntax possibilities, use https://quarto.org/docs/authoring/markdown-basics.html.
  Examples in the documentation range from including images and videos to including margin notes, annotating code, and linking within a document.
-->

{{< include _main_image.qmd >}}

{{< include _ocs_frontmatter.qmd >}}

{{< include _motivation.qmd >}}

{{< include _main_question.qmd >}}

{{< include _los.qmd >}}

::: {.content-hidden unless-meta="include-sections.lo-map"}

{{< include _lo_map.qmd >}}

:::

{{< include _context.qmd >}}

{{< include _containers_intro.qmd >}}

{{< include _data_description.qmd >}}

{{< include _limitations.qmd >}}

{{< include _bioethics.qmd >}}

{{< include _packages.qmd >}}

::: {.content-hidden unless-meta="include-sections.data-import"}

{{< include _data_import.qmd >}}

:::

::: {.content-hidden unless-meta="include-sections.data-exploration"}

{{< include _data_exploration.qmd >}}

:::

::: {.content-hidden unless-meta="include-sections.data-wrangling"}

{{< include _data_wrangling.qmd >}}

:::

::: {.content-hidden unless-meta="include-sections.data-viz"}

{{< include _data_visualization.qmd >}}

:::

::: {.content-hidden unless-meta="include-sections.data-analysis"}

{{< include _data_analysis.qmd >}}

:::

{{< include _summary.qmd >}}

::: {.content-hidden unless-meta="include-sections.main-q-table"}

{{< include _main_qs_answers_table.qmd >}}

:::

{{< include _containers_troubleshooting.qmd >}}

{{< include _suggested_hw.qmd >}}

{{< include _additional_info.qmd >}}

{{< include _glossary_table.qmd >}}

{{< include _bibliography.qmd >}}

## **Session Info**
***

### For the container infrastructure and application steps within this case study

::: {.emphasis_block style="font-family: monospace; font-size: 0.9em; white-space: pre; overflow-x: auto; display: block; line-height: 0.8;"}

```{r}
#| echo: false
#| output: asis

# Replace with your raw GitHub URL
url <- "https://raw.githubusercontent.com/opencasestudies/ocs-bio-containers-analysis/refs/heads/main/full_analysis_results/logs/session_info.txt"

# Fetch lines and print verbatim as Markdown with two spaces in between lines to enforce lines breaks
file_lines <- readLines(url, warn = FALSE)
# Replace every standard space with a non-breaking space HTML entity
file_lines <- gsub(" ", "&nbsp;", file_lines)
formatted_lines <- paste0(file_lines, "  ")
cat(formatted_lines, sep = "\n")
```

:::

### For publishing of this case study

```{r}
devtools::session_info()
```

{{< include _acknowledgements.qmd >}}
